"""环境变量文件生成器"""
from ..templates.base import BaseTemplateGenerator


class EnvGenerator(BaseTemplateGenerator):
    """环境变量文件生成器"""
    
    def generate(self) -> None:
        """生成环境变量文件"""
        # 生成 .env.example
        self._generate_env_example()
        
        # 生成 .env.development
        self._generate_env_development()
        
        # 生成 .env.production
        self._generate_env_production()
    
    def _generate_env_example(self) -> None:
        """生成 .env.example 文件（示例配置）"""
        content = self._build_header("Example Environment Variables")
        content += self._build_app_section(example=True)
        
        if self.config_reader.has_database():
            content += self._build_database_section(example=True)
        
        if self.config_reader.has_auth():
            content += self._build_auth_section(example=True)
        
        # Complete JWT Auth 需要邮件配置
        if self.config_reader.get_auth_type() == "complete":
            content += self._build_email_section(example=True)
        
        if self.config_reader.has_cors():
            content += self._build_cors_section(example=True)
        
        content += self._build_logging_section(example=True)
        
        self.file_ops.create_file(
            file_path="secret/.env.example",
            content=content,
            overwrite=True
        )
    
    def _generate_env_development(self) -> None:
        """生成 .env.development 文件（开发环境配置）"""
        content = self._build_header("Development Environment Variables")
        content += self._build_app_section(env="development")
        
        if self.config_reader.has_database():
            content += self._build_database_section(env="development")
        
        if self.config_reader.has_auth():
            content += self._build_auth_section(env="development")
        
        # Complete JWT Auth 需要邮件配置
        if self.config_reader.get_auth_type() == "complete":
            content += self._build_email_section(env="development")
        
        if self.config_reader.has_cors():
            content += self._build_cors_section(env="development")
        
        content += self._build_logging_section(env="development")
        
        self.file_ops.create_file(
            file_path="secret/.env.development",
            content=content,
            overwrite=True
        )
    
    def _generate_env_production(self) -> None:
        """生成 .env.production 文件（生产环境配置）"""
        content = self._build_header("Production Environment Variables")
        content += "# WARNING: This file contains production secrets\n"
        content += "# DO NOT commit this file to version control\n"
        content += "# Make sure to update all passwords and keys before deploying\n\n"
        content += self._build_app_section(env="production")
        
        if self.config_reader.has_database():
            content += self._build_database_section(env="production")
        
        if self.config_reader.has_auth():
            content += self._build_auth_section(env="production")
        
        # Complete JWT Auth 需要邮件配置
        if self.config_reader.get_auth_type() == "complete":
            content += self._build_email_section(env="production")
        
        if self.config_reader.has_cors():
            content += self._build_cors_section(env="production")
        
        content += self._build_logging_section(env="production")
        
        self.file_ops.create_file(
            file_path="secret/.env.production",
            content=content,
            overwrite=True
        )
    
    def _build_header(self, title: str) -> str:
        """构建文件头部"""
        return f'''# ============================================
# {title}
# ============================================
# Generated by Forge
# DO NOT commit this file to version control
# ============================================

'''
    
    def _build_app_section(self, example: bool = False, env: str = "development") -> str:
        """构建应用配置部分"""
        project_name = self.config_reader.get_project_name()
        
        return f'''# ============================================
# Application Configuration
# ============================================
APP_NAME="{project_name}"
APP_VERSION="1.0.0"
APP_DESCRIPTION="{project_name} API"

'''
    
    def _build_server_section(self, example: bool = False, env: str = "development") -> str:
        """构建服务器配置部分 - 已删除，服务器配置通过命令行参数传递"""
        return ''
    
    def _build_database_section(self, example: bool = False, env: str = "development") -> str:
        """构建数据库配置部分"""
        db_type = self.config_reader.get_database_type()
        project_name = self.config_reader.get_project_name()
        
        if example:
            if db_type == "PostgreSQL":
                return '''# ============================================
# Database Configuration (PostgreSQL)
# ============================================
DATABASE_URL=postgresql+asyncpg://user:password@localhost:5432/dbname

# Connection Pool Configuration
ECHO=false
POOL_PRE_PING=true
POOL_TIMEOUT=30
POOL_SIZE=6
POOL_MAX_OVERFLOW=2

'''
            elif db_type == "MySQL":
                return '''# ============================================
# Database Configuration (MySQL)
# ============================================
DATABASE_URL=mysql+aiomysql://user:password@localhost:3306/dbname

# Connection Pool Configuration
ECHO=false
POOL_PRE_PING=true
POOL_TIMEOUT=30
POOL_SIZE=6
POOL_MAX_OVERFLOW=2

'''
        
        # Development/Production specific
        db_name = f"{project_name}_dev" if env == "development" else f"{project_name}_prod"
        echo = "true" if env == "development" else "false"
        
        if db_type == "PostgreSQL":
            return f'''# ============================================
# Database Configuration (PostgreSQL)
# ============================================
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/{db_name}

# Connection Pool Configuration
ECHO={echo}
POOL_PRE_PING=true
POOL_TIMEOUT=30
POOL_SIZE=6
POOL_MAX_OVERFLOW=2

'''
        elif db_type == "MySQL":
            return f'''# ============================================
# Database Configuration (MySQL)
# ============================================
DATABASE_URL=mysql+aiomysql://root:root@localhost:3306/{db_name}

# Connection Pool Configuration
ECHO={echo}
POOL_PRE_PING=true
POOL_TIMEOUT=30
POOL_SIZE=6
POOL_MAX_OVERFLOW=2

'''
        
        return ''
    
    def _build_auth_section(self, example: bool = False, env: str = "development") -> str:
        """构建认证配置部分"""
        if example:
            content = '''# ============================================
# Authentication Configuration
# ============================================
JWT_SECRET_KEY=your-secret-key-here-change-in-production-min-32-chars
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRATION=1800
'''
            
            if self.config_reader.has_refresh_token():
                content += '''JWT_REFRESH_TOKEN_EXPIRATION=86400
'''
            
            content += '''JWT_ISSUER=demo
JWT_AUDIENCE=demo_users

'''
            return content
        
        # Generate a random secret key for development
        import secrets
        secret_key = secrets.token_urlsafe(32)
        project_name = self.config_reader.get_project_name()
        
        content = f'''# ============================================
# Authentication Configuration
# ============================================
JWT_SECRET_KEY={secret_key}
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRATION=1800
'''
        
        if self.config_reader.has_refresh_token():
            content += '''JWT_REFRESH_TOKEN_EXPIRATION=86400
'''
        
        content += f'''JWT_ISSUER={project_name}
JWT_AUDIENCE={project_name}_users

'''
        return content
    
    def _build_cors_section(self, example: bool = False, env: str = "development") -> str:
        """构建 CORS 配置部分"""
        if example:
            return '''# ============================================
# CORS Configuration
# ============================================
CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080
CORS_ALLOW_CREDENTIALS=true
CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,PATCH,OPTIONS
CORS_ALLOW_HEADERS=*
CORS_EXPOSE_HEADERS=

'''
        
        if env == "development":
            return '''# ============================================
# CORS Configuration
# ============================================
CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080,http://127.0.0.1:3000
CORS_ALLOW_CREDENTIALS=true
CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,PATCH,OPTIONS
CORS_ALLOW_HEADERS=*
CORS_EXPOSE_HEADERS=

'''
        else:
            return '''# ============================================
# CORS Configuration
# ============================================
CORS_ALLOWED_ORIGINS=https://yourdomain.com
CORS_ALLOW_CREDENTIALS=true
CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,PATCH,OPTIONS
CORS_ALLOW_HEADERS=*
CORS_EXPOSE_HEADERS=

'''
    
    def _build_email_section(self, example: bool = False, env: str = "development") -> str:
        """构建邮件配置部分"""
        project_name = self.config_reader.get_project_name()
        
        if example:
            return f'''# ============================================
# Email Configuration (SMTP)
# ============================================
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_HOST_USER=your-email@gmail.com
EMAIL_HOST_PASSWORD=your-app-password
EMAIL_USE_TLS=true
EMAIL_USE_SSL=false
EMAIL_SSL_CERT_REQS=required
EMAIL_TIMEOUT=30
EMAIL_EXPIRATION=3600

# Email From Configuration
EMAIL_FROM_NAME="{project_name}"
EMAIL_FROM_EMAIL=noreply@yourdomain.com

'''
        
        return f'''# ============================================
# Email Configuration (SMTP)
# ============================================
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_HOST_USER=your-email@gmail.com
EMAIL_HOST_PASSWORD=your-app-password
EMAIL_USE_TLS=true
EMAIL_USE_SSL=false
EMAIL_SSL_CERT_REQS=required
EMAIL_TIMEOUT=30
EMAIL_EXPIRATION=3600

# Email From Configuration
EMAIL_FROM_NAME="{project_name}"
EMAIL_FROM_EMAIL=noreply@yourdomain.com

'''
    
    def _build_logging_section(self, example: bool = False, env: str = "development") -> str:
        """构建日志配置部分"""
        if example:
            return '''# ============================================
# Logging Configuration
# ============================================
LOG_LEVEL=INFO
LOG_TO_FILE=false
LOG_FILE_PATH=logs/app.log
LOG_TO_CONSOLE=true
LOG_CONSOLE_LEVEL=INFO
LOG_ROTATION=1 day
LOG_RETENTION_PERIOD=7 days

'''
        
        log_level = "DEBUG" if env == "development" else "INFO"
        log_to_file = "true" if env == "production" else "false"
        
        return f'''# ============================================
# Logging Configuration
# ============================================
LOG_LEVEL={log_level}
LOG_TO_FILE={log_to_file}
LOG_FILE_PATH=logs/app.log
LOG_TO_CONSOLE=true
LOG_CONSOLE_LEVEL={log_level}
LOG_ROTATION=1 day
LOG_RETENTION_PERIOD=7 days

'''
