"""README.md generategenerator"""
from core.decorators import Generator
from ..templates.base import BaseTemplateGenerator


@Generator(
    category="config",
    priority=2,
    description="Generate README.md with project documentation"
)
class ReadmeGenerator(BaseTemplateGenerator):
    """README.md File generator"""
    
    def generate(self) -> None:
        """generate README.md file"""
        project_name = self.config_reader.get_project_name()
        
        content = self._build_header(project_name)
        content += self._build_features_section()
        content += self._build_installation_section()
        content += self._build_structure_section()
        content += self._build_configuration_section()
        content += self._build_api_docs_section()
        content += self._build_development_section()
        content += self._build_license_section()
        
        self.file_ops.create_markdown_file(
            file_path="README.md",
            title=None,
            content=content,
            overwrite=True
        )
    
    def _build_header(self, project_name: str) -> str:
        """Buildheader"""
        return f'''# {project_name}

FastAPI project generated by Forge.

'''
    
    def _build_features_section(self) -> str:
        """Buildfeatures list section"""
        features = []
        
        # database(is nowrequired)
        db_type = self.config_reader.get_database_type()
        orm_type = self.config_reader.get_orm_type()
        features.append(f"- 🗄️ Database: {db_type} with {orm_type}")
        
        if self.config_reader.has_auth():
            auth_type = self.config_reader.get_auth_type()
            features.append(f"- 🔐 Authentication: {auth_type}")
            if self.config_reader.has_refresh_token():
                features.append("- 🔄 Refresh Token support")
        
        if self.config_reader.has_cors():
            features.append("- 🌐 CORS enabled")
        
        if self.config_reader.has_testing():
            features.append("- 🧪 Testing with pytest")
        
        if self.config_reader.has_docker():
            features.append("- 🐳 Docker support")
        
        if self.config_reader.has_dev_tools():
            features.append("- 🛠️ Development tools (Black, Ruff, MyPy)")
        
        return '## Features\n\n' + '\n'.join(features) + '\n\n'
    
    def _build_installation_section(self) -> str:
        """Buildinstallation instructions section"""
        return '''## Installation

### Using uv (Recommended)

```bash
# Install dependencies
uv sync

# Run the application
uv run uvicorn app.main:app --reload
```

### Using pip

```bash
# Create virtual environment
python -m venv .venv
source .venv/bin/activate  # On Windows: .venv\\Scripts\\activate

# Install dependencies
pip install -e .

# Run the application
uvicorn app.main:app --reload
```

'''
    
    def _build_structure_section(self) -> str:
        """Buildprojectstructure section"""
        content = '''## Project Structure

```
.
├── app/
│   ├── __init__.py
│   ├── main.py             # Application entry point
│   ├── core/               # Core configurations
│   │   ├── config/         # Configuration modules
│   │   │   ├── base.py
│   │   │   ├── settings.py
│   │   │   └── modules/    # Config modules (app, database, jwt, etc.)
│   │   ├── database/       # Database connection
│   │   ├── deps.py         # Dependencies
│   │   ├── logger.py       # Logging configuration
│   │   └── security.py     # Security utilities
│   ├── decorators/         # Custom decorators
│   │   └── rate_limit.py   # Rate limiting decorator
│   ├── models/             # Database models
│   ├── schemas/            # Pydantic schemas
│   ├── crud/               # CRUD operations
'''
        
        if self.config_reader.has_auth():
            content += '''│   ├── services/           # Business logic
'''
        
        content += '''│   ├── routers/            # API routes
│   │   └── v1/             # API version 1
│   └── utils/              # Utility functions
'''
        
        if self.config_reader.has_migration():
            content += '''├── alembic/                # Database migrations
│   ├── versions/           # Migration versions
│   └── env.py              # Alembic configuration
'''
        
        content += '''├── static/                 # Static files (images, CSS, JS, etc.)
'''
        
        if self.config_reader.has_testing():
            content += '''├── tests/                  # Test files
│   ├── conftest.py         # Pytest configuration
│   ├── test_main.py        # Main API tests
│   └── api/                # API endpoint tests
'''
        
        if self.config_reader.has_docker():
            content += '''├── Dockerfile              # Docker configuration
├── docker-compose.yml      # Docker Compose configuration
├── .dockerignore           # Docker ignore file
'''
        
        content += '''├── script/                 # Custom scripts (shell script,  etc.)
├── secret/                 # Environment files
│   ├── .env.example        # Environment variables template
│   ├── .env.development    # Development environment
│   └── .env.production     # Production environment
├── static/                 # Static files (images, CSS, JS, etc.)
├── pyproject.toml          # Project dependencies
├── .gitignore              # Git ignore file
└── README.md               # This file
```

'''
        return content
    
    def _build_configuration_section(self) -> str:
        """Buildconfigurationdescriptionpartial"""
        content = '''## Configuration

Copy `.env.example` to `.env` and update the values:

```bash
cp .env.example .env
```

'''
        # databaseconfiguration(is nowrequired)
        content += self._build_database_config()
        
        return content
    
    def _build_database_config(self) -> str:
        """Builddatabaseconfigurationdescription"""
        content = '''### Database Configuration

Update the database connection string in `.env.development` and `.env.production`:

```
DATABASE_URL=postgresql://user:password@localhost:5432/dbname
```

'''
        
        if self.config_reader.has_migration():
            content += '''### Database Migrations

```bash
# Create a new migration
alembic revision --autogenerate -m "description"

# Apply migrations
alembic upgrade head
```

'''
        
        return content
    
    def _build_api_docs_section(self) -> str:
        """Build API documentationpartial"""
        return '''## API Documentation

Once the application is running, visit:

- Swagger UI: http://127.0.0.1:8000/docs
- ReDoc: http://127.0.0.1:8000/redoc

## Features

### Rate Limiting

The project includes a built-in rate limiting decorator to protect your API endpoints:

```python
from app.decorators.rate_limit import rate_limit, rate_limit_strict

# Custom rate limit
@router.get("/api/data")
@rate_limit(max_requests=100, window_seconds=60)
async def get_data(request: Request):
    return {"data": "value"}

# Predefined strict limit (10 requests/minute)
@router.post("/api/action")
@rate_limit_strict
async def perform_action(request: Request):
    return {"status": "success"}
```

**Available decorators:**
- `@rate_limit_strict` - 10 requests per minute
- `@rate_limit_moderate` - 100 requests per minute
- `@rate_limit_relaxed` - 1000 requests per hour

**Custom identifier (e.g., user-based):**
```python
@rate_limit(
    max_requests=50,
    window_seconds=3600,
    identifier_func=lambda req: req.state.user.id
)
async def user_endpoint(request: Request):
    return {"data": "user-specific"}
```

**Note:** The default implementation uses in-memory storage. For production with multiple instances, consider using Redis-based rate limiting.

'''
    
    def _build_development_section(self) -> str:
        """Build development section"""
        content = '## Development\n\n'
        
        if self.config_reader.has_dev_tools():
            content += self._build_dev_tools_section()
        
        if self.config_reader.has_testing():
            content += self._build_testing_section()
        
        if self.config_reader.has_docker():
            content += self._build_docker_section()
        
        return content
    
    def _build_dev_tools_section(self) -> str:
        """Build development tools section"""
        return '''### Code Formatting

```bash
# Format code with Black
black .

# Lint with Ruff
ruff check .

# Type checking with MyPy
mypy .
```

'''
    
    def _build_testing_section(self) -> str:
        """Buildtestdescription"""
        return '''### Running Tests

```bash
# Run all tests
pytest

# Run with coverage
pytest --cov=app tests/
```

'''
    
    def _build_docker_section(self) -> str:
        """Build Docker description"""
        project_name = self.config_reader.get_project_name()
        return f'''### Docker

```bash
# Build image
docker build -t {project_name} .

# Run container
docker run -p 8000:8000 {project_name}
```

'''
    
    def _build_license_section(self) -> str:
        """Build license section"""
        return '''## License

This project was created by [Forge](https://github.com/ning3739/forge) and is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.
'''
