"""README.md 生成器"""
from ..templates.base import BaseTemplateGenerator


class ReadmeGenerator(BaseTemplateGenerator):
    """README.md 文件生成器"""
    
    def generate(self) -> None:
        """生成 README.md 文件"""
        project_name = self.config_reader.get_project_name()
        
        content = self._build_header(project_name)
        content += self._build_features_section()
        content += self._build_installation_section()
        content += self._build_structure_section()
        content += self._build_configuration_section()
        content += self._build_api_docs_section()
        content += self._build_development_section()
        content += self._build_license_section()
        
        self.file_ops.create_markdown_file(
            file_path="README.md",
            title=None,
            content=content,
            overwrite=True
        )
    
    def _build_header(self, project_name: str) -> str:
        """构建头部"""
        return f'''# {project_name}

FastAPI project generated by Forge.

'''
    
    def _build_features_section(self) -> str:
        """构建功能列表部分"""
        features = []
        
        if self.config_reader.has_database():
            db_type = self.config_reader.get_database_type()
            orm_type = self.config_reader.get_orm_type()
            features.append(f"- 🗄️ Database: {db_type} with {orm_type}")
        
        if self.config_reader.has_auth():
            auth_type = self.config_reader.get_auth_type()
            features.append(f"- 🔐 Authentication: {auth_type}")
            if self.config_reader.has_refresh_token():
                features.append("- 🔄 Refresh Token support")
        
        if self.config_reader.has_cors():
            features.append("- 🌐 CORS enabled")
        
        if self.config_reader.has_testing():
            features.append("- 🧪 Testing with pytest")
        
        if self.config_reader.has_docker():
            features.append("- 🐳 Docker support")
        
        if self.config_reader.has_dev_tools():
            features.append("- 🛠️ Development tools (Black, Ruff, MyPy)")
        
        return '## Features\n\n' + '\n'.join(features) + '\n\n'
    
    def _build_installation_section(self) -> str:
        """构建安装说明部分"""
        return '''## Installation

### Using uv (Recommended)

```bash
# Install dependencies
uv sync

# Run the application
uv run uvicorn main:app --reload
```

### Using pip

```bash
# Create virtual environment
python -m venv .venv
source .venv/bin/activate  # On Windows: .venv\\Scripts\\activate

# Install dependencies
pip install -e .

# Run the application
uvicorn main:app --reload
```

'''
    
    def _build_structure_section(self) -> str:
        """构建项目结构部分"""
        content = '''## Project Structure

```
.
├── app/
│   ├── core/           # Core configurations
│   ├── router/         # API routes
│   ├── schemas/        # Pydantic schemas
│   ├── utils/          # Utility functions
'''
        
        if self.config_reader.has_database():
            content += '''│   ├── models/         # Database models
│   ├── crud/           # CRUD operations
'''
        
        if self.config_reader.has_auth():
            content += '''│   ├── services/       # Business logic
'''
        
        content += '''│   └── __init__.py
├── main.py             # Application entry point
'''
        
        if self.config_reader.has_testing():
            content += '''├── tests/              # Test files
'''
        
        content += '''├── .env.example        # Environment variables example
├── pyproject.toml      # Project dependencies
└── README.md           # This file
```

'''
        return content
    
    def _build_configuration_section(self) -> str:
        """构建配置说明部分"""
        content = '''## Configuration

Copy `.env.example` to `.env` and update the values:

```bash
cp .env.example .env
```

'''
        
        if self.config_reader.has_database():
            content += self._build_database_config()
        
        return content
    
    def _build_database_config(self) -> str:
        """构建数据库配置说明"""
        content = '''### Database Configuration

Update the database connection string in `.env`:

```
DATABASE_URL=postgresql://user:password@localhost:5432/dbname
```

'''
        
        if self.config_reader.has_migration():
            content += '''### Database Migrations

```bash
# Create a new migration
alembic revision --autogenerate -m "description"

# Apply migrations
alembic upgrade head
```

'''
        
        return content
    
    def _build_api_docs_section(self) -> str:
        """构建 API 文档部分"""
        return '''## API Documentation

Once the application is running, visit:

- Swagger UI: http://localhost:8000/docs
- ReDoc: http://localhost:8000/redoc

'''
    
    def _build_development_section(self) -> str:
        """构建开发说明部分"""
        content = '## Development\n\n'
        
        if self.config_reader.has_dev_tools():
            content += self._build_dev_tools_section()
        
        if self.config_reader.has_testing():
            content += self._build_testing_section()
        
        if self.config_reader.has_docker():
            content += self._build_docker_section()
        
        return content
    
    def _build_dev_tools_section(self) -> str:
        """构建开发工具说明"""
        return '''### Code Formatting

```bash
# Format code with Black
black .

# Lint with Ruff
ruff check .

# Type checking with MyPy
mypy .
```

'''
    
    def _build_testing_section(self) -> str:
        """构建测试说明"""
        return '''### Running Tests

```bash
# Run all tests
pytest

# Run with coverage
pytest --cov=app tests/
```

'''
    
    def _build_docker_section(self) -> str:
        """构建 Docker 说明"""
        project_name = self.config_reader.get_project_name()
        return f'''### Docker

```bash
# Build image
docker build -t {project_name} .

# Run container
docker run -p 8000:8000 {project_name}
```

'''
    
    def _build_license_section(self) -> str:
        """构建许可证部分"""
        return '''## License

MIT
'''
